# Generated by Django 5.0.6 on 2024-08-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='generated_revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
