# Generated by Django 5.0.6 on 2024-08-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_project_generated_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
